### ISSUE TITLE
checklist of go bag

### ISSUE THREAD

**Issue by papaburgs** [papaburgs/officeminigolf2023#6]
A list of things to bring on Wednesday

- [ ] spare wire/jumper wires
- [ ] gorilla tape
- [ ] krazy glue
- [ ] glue gun
- [ ] battery / power cord
- [ ] usb cords
- [ ] knife
- [ ] pliers/snips/strippers
- [ ] spare cardboard
